name: MLflow Training CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12.7

      - name: Install MLflow
        run: pip install mlflow

      - name: Run MLflow Project
        run: mlflow run MLProject --entry-point main
